### ISSUE TITLE
Semicolons

### ISSUE THREAD

**Issue by JohnPeel** [SRL/SRL-6#110]
Missing Semicolons...

https://github.com/SRL/SRL-6/blob/master/lib/interfaces/powerscreen.simba#L1148
https://github.com/SRL/SRL-6/blob/master/lib/core/mouse.simba#L214
https://github.com/SRL/SRL-6/blob/master/lib/core/mouse.simba#L317

This one could be an else? No clue...
https://github.com/SRL/SRL-6/blob/master/lib/misc/antiban.simba#L1047

**Comment by SRLTheMayor** [comment]
I think this can be closed? All the lines have changed anyway

**Comment by JohnPeel** [comment]
Yeah, I'll close it, it's from awhile back =P
