### ISSUE TITLE
Login error if username is < 25 characters

### ISSUE THREAD

**Issue by SRLJustin** [SRL/SRL-6#129]
If your username is greater then 25 characters and it enters invalid details, it won't delete all the text from the username box, a fix for this would be to revise line 775 of players.simba 

while (countColor(__LOGIN_COLOR_TEXT, tmpBox) > 0) and (c < 25) do

and maybe increase the count

**Comment by SRLJustin** [comment]
Closed - https://github.com/SRL/SRL-6/commit/980e529e65096438db527fd8e1c6e3f5c942e453

**Comment by Zyt3x** [comment]
Did you also increase the length?

**Comment by SRLTheMayor** [comment]
Its inside a loop and won't type anything unless all the text is cleared
