### ISSUE TITLE
Project is not maintained well.

### ISSUE THREAD

**Issue by R030t1** [SRL/SRL-6#284]
Can these changes and the associated commit messages be adequately explained?

* https://github.com/SRL/SRL-6/commit/16dec72d97b5543ed269902eda765731efc1a5b0
* https://github.com/SRL/SRL-6/commit/4298c1269ccab2a748b092b94fafb817359ce9c4
* https://github.com/SRL/SRL-6/commit/a836632a1aa31c6a05b4c6271875038d7c6f3f0b

The include needs maintenance, but these are trivial corrections that do not make sense.

**Comment by TheTS** [comment]
There are no active developers on this project for reasons I won't go into here.

It looks like those commits were to fix compile errors caused by someone not testing their code 👍
