### ISSUE TITLE
Maths behind humanWindMouse

### ISSUE THREAD

**Issue by leonszimmermann** [SRL/SRL-6#296]
I am interested in the maths behind [humanWindMouse](https://github.com/SRL/SRL-6/blob/master/lib/core/mouse.simba#LC199). I found it through research on [StackOverflow](https://codereview.stackexchange.com/questions/138654/human-like-mouse-movement) for an unrelated project. Unfortunately, the code on [StackOverflow](https://codereview.stackexchange.com/questions/138654/human-like-mouse-movement) is a bit messy and I can't quite understand how it works (I also don't know Pascal). I would like to implement it in C# and also understand the maths behind it. I want to call it as follows: humanMouseMove(int x1, int y1, int x2, int y2, int time) and get a [Tuple<int, int>](https://docs.microsoft.com/en-us/dotnet/api/system.tuple-2) of movements (positive or relative x and y movements) in return.
It would be really great if you could give me advice (eg. reference or an explaination).
Thanks in advance!

**Comment by ollydev** [comment]
The original version (and author) is here:
https://github.com/BenLand100/SMART/blob/master/src/EventNazi.java#L201 

You should probably ask on that repository if you want a real explanation.
